backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Extrait", name: "excerpt", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "modules"
    label: "Modules CRMEF"
    folder: "src/modules"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Extrait", name: "excerpt", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
